#!/bin/bash

# Test script to demonstrate the new localhost streaming options

echo "========================================="
echo "      Localhost Streaming Test           "
echo "========================================="

echo "Testing the new localhost streaming options in rtsp_stream.sh"
echo ""
echo "The script now offers three options:"
echo "1. Single server (accessible on both external IP and localhost)"
echo "2. Separate servers (external IP on port 8554, localhost on port 8555)"
echo "3. External IP only"
echo ""
echo "To test this feature:"
echo "1. Run: ./rtsp_stream.sh"
echo "2. Select your streaming source (cameras, video files, or both)"
echo "3. When prompted for localhost options, choose option 1, 2, or 3"
echo ""
echo "Option 1 (Single server):"
echo "  - One RTSP server on port 8554"
echo "  - Accessible via both external IP and localhost"
echo "  - URLs: rtsp://EXTERNAL_IP:8554/stream and rtsp://localhost:8554/stream"
echo ""
echo "Option 2 (Separate servers):"
echo "  - External server on port 8554"
echo "  - Localhost server on port 8555"
echo "  - URLs: rtsp://EXTERNAL_IP:8554/stream and rtsp://localhost:8555/stream"
echo ""
echo "Option 3 (External only):"
echo "  - One RTSP server on port 8554"
echo "  - Only accessible via external IP"
echo "  - URL: rtsp://EXTERNAL_IP:8554/stream"
echo ""
echo "The new multi-stream-server-port binary has been compiled and is ready to use."
echo "It accepts a port number as the first argument."
echo ""
echo "Example usage:"
echo "  ./multi-stream-server-port 8555 /cam1 \"( v4l2src device=/dev/video0 ! ... )\""
echo ""
echo "Press Enter to continue..."
read 